---
all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: "192.168.100.10"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/homelab
    kubernetes:
      children:
        k8s_master:
          hosts:
            k8s-master:
              ansible_host: "192.168.100.100"
              ansible_user: masternode
              ansible_ssh_private_key_file: ~/.ssh/homelab
        k8s_workers:
          hosts:
            k8s-worker-1:
              ansible_host: "192.168.100.101"
              ansible_user: masternode
              ansible_ssh_private_key_file: ~/.ssh/homelab
            k8s-worker-2:
              ansible_host: "192.168.100.102"
              ansible_user: masternode
              ansible_ssh_private_key_file: ~/.ssh/homelab