---
- name: Hello World Test
  hosts: proxmox, kubernetes
  gather_facts: false

  tasks:
    - name: Create hello_world.txt with Hello, World! content
      copy:
        dest: /tmp/hello_world.txt
        content: "Hello, World!\n"